export const informationPages = [
  { slug: 'how-it-works', title: 'A checklist, not an all-clear.', eyebrow: 'How it works', intro: 'A useful planning tool should make uncertainty visible. This pilot separates source reviews, automated collection and your own checklist.', sections: [
    { title: 'Start with a specific visit', text: 'Choose a park, a visit date, an area and an arrival time where needed. The entry checker covers one day of first-entry travel by private vehicle. Existing permits, service reservations, re-entry and other travel modes require direct official review.' },
    { title: 'Know what was actually checked', text: 'Entry guidance is curated from official NPS pages and includes the reviewed text, a source link and the review time. A stored review is not live monitoring. In this pilot, alert collection has not been connected and three parks still need their first entry-rule review.' },
    { title: 'Reviews expire; rules do not carry into another year', text: 'After seven days, the entry checker stops making a current determination from a stored review. Browser freshness labels recalculate even without a new build. A different year, season, missing time or unknown area is not treated as an exemption.' },
    { title: 'The checked feed is never the whole park', text: 'When collection is connected, an empty successful response will mean only that the checked feed returned no alerts. Failed checks retain last-good records with a warning. A missing notice will not be translated into a reopening claim. Area classification, dated applicability and change history still need a later milestone.' },
    { title: 'Your checkmarks are self-reported', text: 'Checklist completion means you marked the items reviewed. It does not verify a booking or guarantee entry, parking, conditions or safety. Selections are kept only in the page, not stored in an account, cookie or local-storage database.' },
  ]},
  { slug: 'sources', title: 'Follow the evidence.', eyebrow: 'Sources & coverage', intro: 'Official-source links stay next to the guidance they support. The pilot is deliberately narrower than the information available on the full NPS website.', sections: [
    { title: 'Reviewed entry guidance', text: 'Yosemite and Rocky Mountain have stored 2026 entry-rule reviews. The park pages retain exact supporting text and an SHA-256 hash of that excerpt. This is not a hash of the full source page. Source update, source review and collection times are not interchangeable.', links: [{ label: 'Yosemite entrance reservations', url: 'https://www.nps.gov/yose/planyourvisit/reservations.htm' }, { label: 'Rocky Mountain timed entry', url: 'https://www.nps.gov/romo/planyourvisit/timed-entry-permit-system.htm' }] },
    { title: 'Automated NPS data — not connected yet', text: 'A tested collector foundation is included in the project, but no live request has been validated and no schedule is enabled. Until that gate passes, automated conditions are labeled not collected.', links: [{ label: 'NPS developer resources', url: 'https://www.nps.gov/subjects/developer/index.htm' }] },
    { title: 'Content-use boundaries', text: 'This pilot uses source-linked facts, short reviewed government-authored text excerpts and original planning explanations. It does not reproduce NPS marks, photographs or unreviewed third-party media. No claim is made to original U.S. Government works. The source-use review is not a blanket clearance for every item on a government website.', links: [{ label: 'NPS copyright and disclaimer information', url: 'https://www.nps.gov/aboutus/disclaimer.htm' }] },
    { title: 'Weather and booking are separate', text: 'No forecast, weather-alert geography, booking inventory or reservation availability is integrated. Links to official providers are starting points, not endorsements or availability confirmations.', links: [{ label: 'National Weather Service', url: 'https://www.weather.gov/' }] },
  ]},
  { slug: 'changes', title: 'Change history comes next.', eyebrow: 'Observation history', intro: 'There is no live observation history to show yet. An initial editorial review is not an observed road or facility change.', sections: [
    { title: 'Not yet collecting consecutive snapshots', text: 'The next collection milestone must validate complete feeds, stable evidence and safe publication before this page can show additions, edits or removals. We will describe a removed notice as no longer in the checked feed, not as a confirmed reopening.' },
    { title: 'Check current information directly', text: 'Use the official conditions link on each park page. Do not interpret an empty history page as evidence that nothing has changed.', links: [{ label: 'Explore the pilot parks', url: '/parks/' }] },
  ]},
  { slug: 'about', title: 'Preparation without false certainty.', eyebrow: 'About the project', intro: 'Park Readiness is an independent development pilot for travelers planning visits to U.S. national parks.', sections: [
    { title: 'Five parks first', text: 'The initial inventory is Yosemite, Rocky Mountain, Yellowstone, Zion and Grand Canyon. This is a testable pilot selection, not a popularity ranking or complete national-park directory.' },
    { title: 'Independent and transparent', text: 'This project is not affiliated with or endorsed by the National Park Service. It does not claim field visits or independent verification of current conditions. Sources, review times and missing coverage remain visible.' },
    { title: 'No advertising during the pilot', text: 'The site contains no active advertising, analytics tracking or paid booking integrations. Any future advertising would require a separate publisher, privacy and placement review.' },
  ]},
  { slug: 'privacy', title: 'Keep planning simple.', eyebrow: 'Pilot privacy information', intro: 'The current application does not require an account and does not send your date, area, arrival time or checklist choices to a server.', sections: [
    { title: 'Page-only choices', text: 'Interactive choices are held in browser memory for the page session. The pilot does not persist them in cookies or local storage. Reset the checklist to clear its checkmarks. A fresh page load starts again.' },
    { title: 'No ad or analytics code', text: 'There are no advertising tags, analytics scripts, third-party fonts, embedded maps or social-media widgets in this version.' },
    { title: 'Hosting and external links', text: 'Any eventual hosting provider may process ordinary request logs. A production host and its practices still need to be documented before launch. Following a link to NPS, NWS or GitHub takes you to a separate service with its own privacy practices.' },
    { title: 'Do not submit sensitive information', text: 'The corrections route links to the public project issue tracker. Do not include API keys, reservation confirmation codes, identity documents or private travel details.' },
  ]},
  { slug: 'terms', title: 'Use this as a starting point.', eyebrow: 'Use & limitations', intro: 'This development pilot is an informational planning aid. It is not an official park service, emergency-warning system or booking platform.', sections: [
    { title: 'Confirm with the official source', text: 'Access requirements and conditions may change after a review. Check official guidance immediately before travel and follow on-site instructions. A date-check result addresses only the specific stored rule, not every condition of entry.' },
    { title: 'Incomplete coverage is explicit', text: 'No assurance is made that every notice, exception, activity permit, fee component or facility condition is included. Three of the five parks still lack curated entry rules, and automated alert collection is not live.' },
    { title: 'Production terms are a later gate', text: 'This page describes the limitations of the current pilot. Production publisher details, hosting disclosures and any advertising-related requirements must be reviewed before public launch.' },
  ]},
  { slug: 'corrections', title: 'Help make the record better.', eyebrow: 'Corrections', intro: 'Found a broken link, outdated rule or misleading explanation? Report the specific page and the official evidence.', sections: [
    { title: 'Report a source-backed correction', text: 'Include the park page, the wording that needs review, the relevant date and an official source link. A GitHub sign-in may be required. Do not include personal information or private booking confirmations.', links: [{ label: 'Open a correction on GitHub', url: 'https://github.com/Vasuki8/us-national-park-trip-readiness-tracker/issues/new' }] },
    { title: 'Urgent conditions are not handled here', text: 'This issue tracker is not an emergency or real-time reporting channel. Follow official park guidance and use the appropriate local emergency service for immediate assistance.' },
  ]},
];
