import { coverageInput, rules, notes, parks } from './data';
import { summarizeCoverage } from './source-coverage';
const coverage = summarizeCoverage(coverageInput, new Date());
const sourceLinks = [...new Map([...rules, ...notes].map((review) => [review.evidence.url, { label: `${parks.find((park) => park.code === review.park_code)?.name ?? review.park_code} entry source`, url: review.evidence.url }])).values()];
export const informationPages = [
  { slug: 'how-it-works', title: 'A checklist, not an all-clear.', eyebrow: 'How it works', intro: 'A useful planning tool should make uncertainty visible. This pilot separates source reviews, automated collection and your own checklist.', sections: [
    { title: 'Start with a specific visit', text: 'Choose a park, a visit date, an area and an arrival time where needed. The entry checker covers one day of first-entry travel by private vehicle. Existing permits, service reservations, re-entry and other travel modes require direct official review.' },
    { title: 'Know what was actually checked', text: `Entry guidance is curated from official NPS pages and includes the reviewed text, a source link and the review time. ${coverage.storedReviewParks} parks have stored source reviews; ${coverage.datedRuleParks} have dated rules. These counts describe evidence availability, not current access. A stored review is not live monitoring.` },
    { title: 'Undated guidance stays undated', text: 'Some official general-entry statements do not publish an effective date range. We retain those as source observations, with their review dates, rather than inventing a calendar year. They do not enter the date checker and cannot automatically grant an exemption for your trip.' },
    { title: 'Reviews expire; rules do not carry into another year', text: 'After seven days, the entry checker stops making a current determination from a stored review. Alert snapshots need refreshing when their last successful check is older than four hours. Browser freshness labels recalculate without fetching new source data or publishing a new observation. A different year, season, missing time or unknown area is not treated as an exemption. Without JavaScript, age labels reflect the displayed build time.' },
    { title: 'The checked feed is never the whole park', text: 'An empty successful response means only that the checked feed returned no alerts. Failed checks retain last-good records with a warning. Alert snapshots and recorded history are published through reviewed manual updates. The history timeline distinguishes a first baseline from later notice differences; a removed notice is not a confirmed reopening. Area classification and dated applicability remain unverified.' },
    { title: 'Your checkmarks are self-reported', text: 'Checklist completion means you marked the items reviewed. It does not verify a booking or guarantee entry, parking, conditions or safety. Selections are kept only in the page, not stored in an account, cookie or local-storage database.' },
  ]},
  { slug: 'sources', title: 'Follow the evidence.', eyebrow: 'Sources & coverage', intro: 'Official-source links stay next to the guidance they support. The pilot is deliberately narrower than the information available on the full NPS website.', sections: [
    { title: 'Reviewed entry guidance', text: `${coverage.storedReviewParks} parks have stored entry-source reviews, but only ${coverage.datedRuleParks} have dated rules used by the checker. Undated observations remain separate. Park pages retain exact supporting text and an SHA-256 hash of that excerpt, not of the full source page. Source update, source review and collection times are not interchangeable.`, links: sourceLinks },
    { title: 'NPS alert snapshots and recorded checks', text: 'Reviewed NPS alert snapshots and their observation history are published for the five pilot parks through manual updates. No collection schedule or automatic publication is enabled. This is not continuous monitoring: use the original check times and freshness labels, and confirm current conditions with NPS.', links: [{ label: 'NPS developer resources', url: 'https://www.nps.gov/subjects/developer/index.htm' }] },
    { title: 'Content-use boundaries', text: 'This pilot uses source-linked facts, short reviewed government-authored text excerpts and original planning explanations. It does not reproduce NPS marks, photographs or unreviewed third-party media. No claim is made to original U.S. Government works. The source-use review is not a blanket clearance for every item on a government website.', links: [{ label: 'NPS copyright and disclaimer information', url: 'https://www.nps.gov/aboutus/disclaimer.htm' }] },
    { title: 'Weather and booking are separate', text: 'No forecast, weather-alert geography, booking inventory or reservation availability is integrated. Links to official providers are starting points, not endorsements or availability confirmations.', links: [{ label: 'National Weather Service', url: 'https://www.weather.gov/' }] },
  ]},
  { slug: 'changes', title: 'Notice history, with context.', eyebrow: 'Observation history', intro: 'See what our checked feeds recorded, with a clear distinction between evidence and current conditions. This history is published through reviewed manual updates, not continuous monitoring.', sections: [
    { title: 'A record of checks, not an all-clear', text: 'The first accepted feed is a baseline, not a new closure event. Later differences can show a notice added, edited or no longer present in that feed. A removal is not a confirmed reopening. Failed checks retain earlier accepted evidence and do not generate notice removals.' },
    { title: 'Check current information directly', text: 'An empty timeline does not mean that nothing has changed at the park. Follow the official conditions links below. Observation timestamps are not NPS update times or the effective dates of restrictions, and a bounded view explicitly identifies omitted checks and changes.', links: [{ label: 'Explore the pilot parks', url: '/parks/' }] },
  ]},
  { slug: 'about', title: 'Preparation without false certainty.', eyebrow: 'About the project', intro: 'Park Readiness is an independent development pilot for travelers planning visits to U.S. national parks.', sections: [
    { title: 'Five parks first', text: 'The initial inventory is Yosemite, Rocky Mountain, Yellowstone, Zion and Grand Canyon. This is a testable pilot selection, not a popularity ranking or complete national-park directory.' },
    { title: 'Independent and transparent', text: 'This project is not affiliated with or endorsed by the National Park Service. It does not claim field visits or independent verification of current conditions. Sources, review times and missing coverage remain visible.' },
    { title: 'No advertising during the pilot', text: 'The site contains no active advertising, analytics tracking or paid booking integrations. Any future advertising would require a separate publisher, privacy and placement review.' },
  ]},
  { slug: 'privacy', title: 'Keep planning simple.', eyebrow: 'Pilot privacy information', intro: 'The current application does not require an account and does not send your date, area, arrival time or checklist choices to a server.', sections: [
    { title: 'Page-only choices', text: 'Interactive choices are held in browser memory for the page session. The pilot does not persist them in cookies or local storage. Reset the checklist to clear its checkmarks. A fresh page load starts again.' },
    { title: 'No ad or analytics code', text: 'There are no advertising tags, analytics scripts, third-party fonts, embedded maps or social-media widgets in this version.' },
    { title: 'Hosting and external links', text: 'The pilot is hosted on GitHub Pages. GitHub may receive ordinary web requests when you load the site. Following a link to NPS, NWS or GitHub takes you to a separate service with its own privacy practices.' },
    { title: 'Do not submit sensitive information', text: 'The corrections route links to the public project issue tracker. Do not include API keys, reservation confirmation codes, identity documents or private travel details.' },
  ]},
  { slug: 'terms', title: 'Use this as a starting point.', eyebrow: 'Use & limitations', intro: 'This development pilot is an informational planning aid. It is not an official park service, emergency-warning system or booking platform.', sections: [
    { title: 'Confirm with the official source', text: 'Access requirements and conditions may change after a review. Check official guidance immediately before travel and follow on-site instructions. A date-check result addresses only the specific stored rule, not every condition of entry.' },
    { title: 'Incomplete coverage is explicit', text: 'No assurance is made that every notice, exception, activity permit, fee component or facility condition is included. An undated general-entry source review is not a date-specific rule. Alert snapshots are published through reviewed manual updates; conditions are not continuously monitored.' },
    { title: 'Future publishing changes require review', text: 'This page describes the limitations of the current hosted pilot. Search indexing, advertising and recurring operations each require a separate review and operator decision before they are enabled.' },
  ]},
  { slug: 'corrections', title: 'Help make the record better.', eyebrow: 'Corrections', intro: 'Found a broken link, outdated rule or misleading explanation? Report the specific page and the official evidence.', sections: [
    { title: 'Report a source-backed correction', text: 'Include the park page, the wording that needs review, the relevant date and an official source link. A GitHub sign-in may be required. Do not include personal information or private booking confirmations.', links: [{ label: 'Open a correction on GitHub', url: 'https://github.com/Vasuki8/us-national-park-trip-readiness-tracker/issues/new' }] },
    { title: 'Urgent conditions are not handled here', text: 'This issue tracker is not an emergency or real-time reporting channel. Follow official park guidance and use the appropriate local emergency service for immediate assistance.' },
  ]},
];
